export const cityOptions = [
  { value: "", label: "All" },
  { value: "new-york-ny", label: "New York, NY" },
  { value: "los-angeles-ca", label: "Los Angeles, CA" },
  { value: "chicago-il", label: "Chicago, IL" },
  { value: "houston-tx", label: "Houston, TX" },
  { value: "phoenix-az", label: "Phoenix, AZ" },
  { value: "philadelphia-pa", label: "Philadelphia, PA" },
  { value: "san-antonio-tx", label: "San Antonio, TX" },
  { value: "san-diego-ca", label: "San Diego, CA" },
  { value: "dallas-tx", label: "Dallas, TX" },
  { value: "jacksonville-fl", label: "Jacksonville, FL" },
  { value: "austin-tx", label: "Austin, TX" },
  { value: "fort-worth-tx", label: "Fort Worth, TX" },
  { value: "san-jose-ca", label: "San Jose, CA" },
  { value: "columbus-oh", label: "Columbus, OH" },
  { value: "charlotte-nc", label: "Charlotte, NC" },
  { value: "indianapolis-in", label: "Indianapolis, IN" },
  { value: "san-francisco-ca", label: "San Francisco, CA" },
  { value: "seattle-wa", label: "Seattle, WA" },
  { value: "denver-co", label: "Denver, CO" },
  { value: "oklahoma-city-ok", label: "Oklahoma City, OK" },
  { value: "nashville-tn", label: "Nashville, TN" },
  { value: "washington-dc", label: "Washington, DC" },
  { value: "el-paso-tx", label: "El Paso, TX" },
  { value: "las-vegas-nv", label: "Las Vegas, NV" },
  { value: "boston-ma", label: "Boston, MA" },
  { value: "detroit-mi", label: "Detroit, MI" },
  { value: "portland-or", label: "Portland, OR" },
  { value: "louisville-ky", label: "Louisville, KY" },
  { value: "memphis-tn", label: "Memphis, TN" },
  { value: "baltimore-md", label: "Baltimore, MD" },
  { value: "milwaukee-wi", label: "Milwaukee, WI" },
  { value: "albuquerque-nm", label: "Albuquerque, NM" },
  { value: "tucson-az", label: "Tucson, AZ" },
  { value: "fresno-ca", label: "Fresno, CA" },
  { value: "sacramento-ca", label: "Sacramento, CA" },
  { value: "mesa-az", label: "Mesa, AZ" },
  { value: "atlanta-ga", label: "Atlanta, GA" },
  { value: "kansas-city-mo", label: "Kansas City, MO" },
  { value: "colorado-springs-co", label: "Colorado Springs, CO" },
  { value: "omaha-ne", label: "Omaha, NE" },
  { value: "raleigh-nc", label: "Raleigh, NC" },
  { value: "miami-fl", label: "Miami, FL" },
  { value: "virginia-beach-va", label: "Virginia Beach, VA" },
  { value: "long-beach-ca", label: "Long Beach, CA" },
  { value: "oakland-ca", label: "Oakland, CA" },
  { value: "minneapolis-mn", label: "Minneapolis, MN" },
  { value: "bakersfield-ca", label: "Bakersfield, CA" },
  { value: "tulsa-ok", label: "Tulsa, OK" },
  { value: "tampa-fl", label: "Tampa, FL" },
  { value: "arlington-tx", label: "Arlington, TX" },
  { value: "wichita-ks", label: "Wichita, KS" },
  { value: "aurora-co", label: "Aurora, CO" },
  { value: "new-orleans-la", label: "New Orleans, LA" },
  { value: "cleveland-oh", label: "Cleveland, OH" },
  { value: "honolulu-hi", label: "Honolulu, HI" },
  { value: "anaheim-ca", label: "Anaheim, CA" },
  { value: "henderson-nv", label: "Henderson, NV" },
  { value: "orlando-fl", label: "Orlando, FL" },
  { value: "lexington-ky", label: "Lexington, KY" },
  { value: "stockton-ca", label: "Stockton, CA" },
  { value: "riverside-ca", label: "Riverside, CA" },
  { value: "corpus-christi-tx", label: "Corpus Christi, TX" },
  { value: "irvine-ca", label: "Irvine, CA" },
  { value: "cincinnati-oh", label: "Cincinnati, OH" },
  { value: "santa-ana-ca", label: "Santa Ana, CA" },
  { value: "newark-nj", label: "Newark, NJ" },
  { value: "st-paul-mn", label: "St. Paul, MN" },
  { value: "pittsburgh-pa", label: "Pittsburgh, PA" },
  { value: "greensboro-nc", label: "Greensboro, NC" },
  { value: "durham-nc", label: "Durham, NC" },
  { value: "lincoln-ne", label: "Lincoln, NE" },
  { value: "jersey-city-nj", label: "Jersey City, NJ" },
  { value: "plano-tx", label: "Plano, TX" },
  { value: "anchorage-ak", label: "Anchorage, AK" },
  { value: "north-las-vegas-nv", label: "North Las Vegas, NV" },
  { value: "st-louis-mo", label: "St. Louis, MO" },
  { value: "madison-wi", label: "Madison, WI" },
  { value: "chandler-az", label: "Chandler, AZ" },
  { value: "gilbert-az", label: "Gilbert, AZ" },
  { value: "reno-nv", label: "Reno, NV" },
  { value: "buffalo-ny", label: "Buffalo, NY" },
  { value: "chula-vista-ca", label: "Chula Vista, CA" },
  { value: "fort-wayne-in", label: "Fort Wayne, IN" },
  { value: "lubbock-tx", label: "Lubbock, TX" },
  { value: "toledo-oh", label: "Toledo, OH" },
  { value: "st-petersburg-fl", label: "St. Petersburg, FL" },
  { value: "laredo-tx", label: "Laredo, TX" },
  { value: "irving-tx", label: "Irving, TX" },
  { value: "chesapeake-va", label: "Chesapeake, VA" },
  { value: "glendale-az", label: "Glendale, AZ" },
  { value: "winston-salem-nc", label: "Winston-Salem, NC" },
  { value: "port-st-lucie-fl", label: "Port St. Lucie, FL" },
  { value: "scottsdale-az", label: "Scottsdale, AZ" },
  { value: "garland-tx", label: "Garland, TX" },
  { value: "boise-city-id", label: "Boise City, ID" },
  { value: "norfolk-va", label: "Norfolk, VA" },
  { value: "spokane-wa", label: "Spokane, WA" },
  { value: "richmond-va", label: "Richmond, VA" },
  { value: "fremont-ca", label: "Fremont, CA" },
  { value: "huntsville-al", label: "Huntsville, AL" },
];
